### ISSUE TITLE
Project decisions

### ISSUE THREAD

**Issue by vtdat** [vCloud-DFTBA/faythe-ui#1]
There are some points that we have to discuss and agree on:

* Project language?
* Framework (if any)
* Structure
* Features

@ntk148v

**Comment by ntk148v** [comment]
## Project language & Framework

How about [VueJs](https://vuejs.org/)? In fact that we can build a UI with pure golang library: https://gowebexamples.com/templates/ but learning something new is always worthy. 

FYI, ManhVD uses [ReactJS](https://reactjs.org/).

## Structure

I think about moving UI back to the origin Faythe repository. Therefore, we can build once, no more deployment step is needed:

https://github.com/tdewolff/go-vue-template/tree/master/web

**Comment by vtdat** [comment]
Backend: Go\

Frontend: Vuejs, Vue Material.
